Web/WebApp/Controllers/AnuncioWebMotorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMotors.Application;
using WebMotors.ViewModel;
using WebMotors.Helpers;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace WebMotors.Controllers
{
    public class AnuncioWebMotorsController : BaseController
    {
        private readonly AnuncioWebMotorsApp _app;
        public AnuncioWebMotorsController(AnuncioWebMotorsApp app)
        {
            _app = app;
        }
        public async Task<IActionResult> Index(int page = 0, int pageSize = 30, string textSearch = "", string orderBy = "Id", bool ascending = true)
        {
            var result = new PagedResult<AnuncioWebMotorsViewModel>();

            try
            {
                result = await _app.GetAllAsync(page, pageSize, textSearch, orderBy, ascending);
            }
            catch (Exception ex)
            {
                Log(ex, "tb_AnuncioWebmotorsController.Index");
            }
            return View(result);
        }

        [HttpGet]
        public async Task<IActionResult> Table(int page = 0, int pageSize = 30, string textSearch = "", string orderBy = "Id", bool ascending = true)
        {
            var result = new PagedResult<AnuncioWebMotorsViewModel>();

            try
            {
                result = await _app.GetAllAsync(page, pageSize, textSearch, orderBy, ascending);

                return PartialView(result);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua solicitação.");
                Log(ex, "tb_AnuncioWebmotorsController.Index");
            }
            return SmartResult(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var vm = new AnuncioWebMotorsViewModel();
            return SmartResult(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AnuncioWebMotorsViewModel vm)
        {
            if (!ModelState.IsValid)
                return SmartResult(vm);

            try
            {
                _app.Create(vm);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição.");
                Log(ex, "tb_AnuncioWebmotorsController.Create.Post");
            }
            return SmartResult(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var vm = await _app.GetAsync(id);
            return SmartResult(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AnuncioWebMotorsViewModel vm)
        {
            if (!ModelState.IsValid)
                return SmartResult(vm);

            try
            {
                _app.Edit(vm);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição.");
                Log(ex, "tb_AnuncioWebmotorsController.Create.Post");
            }
            return SmartResult(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            bool deleted = false;
            try
            {
                _app.Delete(id);
                deleted = true;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição.");
                Log(ex, "tb_AnuncioWebmotorsController.Create.Post");
            }
            return SmartResult(deleted, deleted);
        }

        [HttpGet]
        public async Task<JsonResult> GetModelos(int idMarca)
        {
            HttpClient client = new HttpClient();
            List<ModeloViewModel> model = null;

            try
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("User-Agent", "Teste");

                var stringTask = client.GetStringAsync("http://desafioonline.webmotors.com.br/api/OnlineChallenge/Model?MakeID="+idMarca);

                var msg = await stringTask;
                model = JsonConvert.DeserializeObject<List<ModeloViewModel>>(msg);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição. "+ ex.Message);
            }

            return Json(model);

        }

        [HttpGet]
        public async Task<JsonResult> GetVersao(int idModelo)
        {
            HttpClient client = new HttpClient();
            List<VersaoViewModel> model = null;

            try
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("User-Agent", "Teste");

                var stringTask = client.GetStringAsync("http://desafioonline.webmotors.com.br/api/OnlineChallenge/Version?ModelID=" + idModelo);

                var msg = await stringTask;
                model = JsonConvert.DeserializeObject<List<VersaoViewModel>>(msg);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição. " + ex.Message);
            }

            return Json(model);

        }

        public IActionResult DropDownList(int? id)
        {
            return ViewComponent("tb_AnuncioWebmotorsDropDownList", new { id = id });
        }
    }
}

Web/WebApp/ViewComponent/MarcaDropDownListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMotors.Application;
using WebMotors.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;

namespace WebMotors.ViewComponent
{
    public class MarcaDropDownListViewComponent : Microsoft.AspNetCore.Mvc.ViewComponent
    {

        public MarcaDropDownListViewComponent()
        {
        }
        public async Task<IViewComponentResult> InvokeAsync(int? id, string tagName = "selectMarca")
        {
            var ddl = new List<SelectListItem>();

            HttpClient client = new HttpClient();

            try
            {
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                client.DefaultRequestHeaders.Add("User-Agent", "Teste");

                var stringTask = client.GetStringAsync("http://desafioonline.webmotors.com.br/api/OnlineChallenge/Make");

                var msg = await stringTask;
                var model = JsonConvert.DeserializeObject<List<MarcaViewModel>>(msg);

                foreach (var item in model)
                {
                    var listItem = new SelectListItem()
                    {
                        Value = item.Id.ToString(),
                        Text = item.Name,
                        Selected = (id.HasValue && item.Id == id.Value)
                    };
                    ddl.Add(listItem);
                }
                ViewBag.Nome = tagName;
                ViewBag.TextoAlternativo = "Selecione uma marca";
                ViewBag.CssClass = "basic-autocomplete";
                ViewBag.SelectedValue = id;
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Ocorreu um erro ao processar sua requisição. " + ex.Message);
            }
            return View("~/Views/Shared/_DropDownList.cshtml", ddl);
        }
    }
}

Web/WebApp/Views/AnuncioWebMotors/Create.cshtml
@model AnuncioWebMotorsViewModel
@{
    ViewData["Title"] = "Create";
}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col s12 text-red">
        @Html.ValidationSummary()
    </div>
</div>
<div class="row">
    <form class="col s12" action="/AnuncioWebMotors/create/" method="post" id="item-form">
        @Html.AntiForgeryToken()
        <div class="row">
            @await Component.InvokeAsync("MarcaDropDownList")
            <br />
            <br />
            <select class="js-example-basic-single" id="selectModelo">
                <option value="" disabled selected>Selecione o Modelo</option>
            </select>
            <br />
            <br />
            <select class="js-example-basic-single" id="selectVersao">
                <option value="" disabled selected>Selecione a Versão</option>
            </select>

            @Html.HiddenFor(t => t.Marca)
            @Html.HiddenFor(t => t.Modelo)
            @Html.HiddenFor(t => t.Versao)

            <div class="input-field col s12">
                <input asp-for="@Model.Ano" type="number" class="validate" />
                <label asp-for="@Model.Ano"></label>
                <span asp-validation-for="@Model.Ano"></span>
            </div>
            <div class="input-field col s12">
                <input asp-for="@Model.Quilometragem" type="number" class="validate" />
                <label asp-for="@Model.Quilometragem"></label>
                <span asp-validation-for="@Model.Quilometragem"></span>
            </div>
            <div class="input-field col s12">
                <input asp-for="@Model.Observacao" type="text" class="validate" />
                <label asp-for="@Model.Observacao"></label>
                <span asp-validation-for="@Model.Observacao"></span>
            </div>
        </div>
    </form>
</div>

Web/WebApp/Views/AnuncioWebMotors/Edit.cshtml
@model AnuncioWebMotorsViewModel
@{
    ViewData["Title"] = "Edit";
}
<div class="row">
    <div class="col s12 text-red">
        @Html.ValidationSummary()
    </div>
</div>
<div class="row">
    <form class="col s12" action="/AnuncioWebMotors/edit/" method="post" id="item-form">
        @Html.AntiForgeryToken()
        <input type="hidden" asp-for="@Model.Id" />
        <div class="row">
            @await Component.InvokeAsync("MarcaDropDownList")
            <br />
            <br />
            <select class="js-example-basic-single" id="selectModelo">
                <option value="" disabled selected>Selecione o Modelo</option>
            </select>
            <br />
            <br />
            <select class="js-example-basic-single" id="selectVersao">
                <option value="" disabled selected>Selecione a Versão</option>
            </select>

            @Html.HiddenFor(t => t.Marca)
            @Html.HiddenFor(t => t.Modelo)
            @Html.HiddenFor(t => t.Versao)

            <div class="input-field col s12">
                <input asp-for="@Model.Ano" type="number" class="validate" />
                <label asp-for="@Model.Ano"></label>
                <span asp-validation-for="@Model.Ano"></span>
            </div>
            <div class="input-field col s12">
                <input asp-for="@Model.Quilometragem" type="number" class="validate" />
                <label asp-for="@Model.Quilometragem"></label>
                <span asp-validation-for="@Model.Quilometragem"></span>
            </div>
            <div class="input-field col s12">
                <input asp-for="@Model.Observacao" type="text" class="validate" />
                <label asp-for="@Model.Observacao"></label>
                <span asp-validation-for="@Model.Observacao"></span>
            </div>
        </div>
    </form>
</div>

Web/WebApp/Views/AnuncioWebMotors/Index.cshtml
@model PagedResult<AnuncioWebMotorsViewModel>

@{
    ViewData["Title"] = "Anuncios";
}
<h2>Anúncios</h2>
@Html.AntiForgeryToken()
<div id="table-container">
    @Html.Partial("Table", Model)
</div>
<!-- Modal Structure -->
<div id="item-modal" class="modal modal-fixed-footer">
    <div class="modal-content" id="item-modal-content">

    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat" id="btn-save">Salvar</a>
    </div>
</div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large waves-effect waves-light indigo" id="create-item" data-url="/anunciowebmotors/"><i class="material-icons">add</i></a>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('.js-example-basic-single').select2();
        });

        $(document).on("change", "#selectMarca", function (e) {
            e.preventDefault();
            var idMarca = $("#selectMarca").val();
            GetModelos(idMarca);
            var marca = $("#selectMarca option:selected").text();
            $("#Marca").val(marca);
        });

        $(document).on("change", "#selectModelo", function (e) {
            e.preventDefault();
            var idModelo = $("#selectModelo").val();
            GetVersao(idModelo);
            var modelo = $("#selectModelo option:selected").text();
            $("#Modelo").val(modelo);
        });

        $(document).on("change", "#selectVersao", function (e) {
            e.preventDefault();
            var versao = $("#selectVersao option:selected").text();
            $("#Versao").val(versao);
        });

        function GetModelos(idMarca) {
            var selectbox = $('#selectModelo');
            selectbox.find('option').remove();
            var url = '/anunciowebmotors/getmodelos?idMarca=' + idMarca;

            $.get(url, function (data) {
                $('<option>').val("").text("Selecione o Modelo").attr("disabled", "disabled").attr("selected", "selected").appendTo(selectbox);
                $.each(data, function (key, value) {
                    $('<option>').val(value.id).text(value.name).appendTo(selectbox);
                });
            });
        }

        function GetVersao(idModelo) {
            var selectbox = $('#selectVersao');
            selectbox.find('option').remove();
            var url = '/anunciowebmotors/getVersao?idModelo=' + idModelo;

            $.get(url, function (data) {
                $('<option>').val("").text("Selecione a Versão").attr("disabled", "disabled").attr("selected", "selected").appendTo(selectbox);
                $.each(data, function (key, value) {
                    $('<option>').val(value.id).text(value.name).appendTo(selectbox);
                });
            });
        }
    </script>
}

Web/WebApp/Views/AnuncioWebMotors/Table.cshtml
@model PagedResult<AnuncioWebMotorsViewModel>
@{
    Layout = null;
}
<table class="table table-stripped" id="table-content" data-url="/anunciowebmotors/table/">
    <thead>
        <tr>
            <th>Id</th>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Versão</th>
            <th>Ano</th>
            <th>Quilometragem</th>
            <th>Observação</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Itens != null)
        {
            foreach (var item in Model.Itens)
            {
                <tr data-id="@item.Id">
                    <td>@item.Id</td>
                    <td>@item.Marca</td>
                    <td>@item.Modelo</td>
                    <td>@item.Versao</td>
                    <td>@item.Ano</td>
                    <td>@item.Quilometragem</td>
                    <td>@item.Observacao</td>
                    <td>
                        <a class="btn-tiny btn-floating waves-effect waves-light blue edit-item" href="#" data-id="@item.Id"><i class="tiny material-icons">edit</i></a>
                        <a class="btn-tiny btn-floating waves-effect waves-light red delete-item" href="#" data-id="@item.Id"><i class="tiny material-icons">delete</i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>